### ISSUE TITLE
multi-platforms support 

### ISSUE THREAD

**Issue by lokinfey** [henon/Python.Included#1]
I think we need multi-platforms support~~~~~~~ just like macos

**Comment by henon** [comment]
We need a volunteer who owns a Mac

**Comment by CircuitCraft42** [comment]
I think the biggest limitation would be the lack of a portable Python distribution for other systems (Linux [might be doable](https://stackoverflow.com/q/11249901/9919745), MacOS, [probably not](https://stackoverflow.com/q/4414484/9919745).

**Comment by henon** [comment]
I think this can be closed? There is Linux support now, although I couldn't personally test it

**Comment by axtimhaus** [comment]
Sorry if I am just blind, but where is the Linux support?
I am trying now for hours to get it to work under ArchLinux. The standard python-3.7.3-embed-amd64.zip is compiled for Windows I guess and therefor not usable. In the release folders of python only source is available for Linux. Do I have to compile it myself and use it as EmbeddedResource?

**Comment by henon** [comment]
Yes. I guess so. Or you install python via the native package management of your linux distri.

Sorry, I meant the deployment mechanism, If you look at the Python.Deployment project, there is code for starting commands using bash instead of CMD.exe

**Comment by axtimhaus** [comment]
Ok I will try.
I want to have it embedded to be independent of installed packages in the system.
But now I got it to work with system-wide Python. With Python 3.8 and pythonnet_netstandard_py38_linux installed, there was the problem not finding the python3.8m lib. I searched for it and found, that in Python 3.8 the m-suffix was removed [source](https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes). As you are also maintainer of the pythonnet_netstandard_py38_linux package, this may be interesting for you. Just remove the PYTHON_WITH_PYMALLOC constant during build of pythonnet and pythonnet searches for the correct binary.

**Comment by henon** [comment]
Remove PYTHON_WITH_PYMALLOC only for 3.8 linux?

**Comment by axtimhaus** [comment]
I think also for Mac, but I don't know cause I don't own one.
The Windows Version searches for pythonXX.dll, so that should work. On Linux and Mac it is searched for pythonX.Xm. This is correct for Python <= 3.7.x, but not anymore for 3.8.

**Comment by henon** [comment]
@axtimhaus I removed pymalloc from linux and mac versions of pythonnet for py3.8. check out the pythonnet nuget v2.5.1.1

**Comment by henon** [comment]
according to #23 python 3.8 for linux is working now
