### ISSUE TITLE
Exception upon SetupPython

### ISSUE THREAD

**Issue by StijnVA** [henon/Python.Included#10]
Included the nuget and a program as simple as
```
  static async Task Main(string[] args)
        {
            await Installer.SetupPython();
```

results in:
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Python.Runtime.NETStandard, Version=3.7.0.0, Culture=neutral, PublicKeyToken=null'.

What am I missing?

**Comment by henon** [comment]
Can you give more details? Operating System, which .Net Framework (Framework/ Standard or Core)?

**Comment by StijnVA** [comment]
OS: Windows 10 Pro 64-bit

![image](https://user-images.githubusercontent.com/5576173/88257056-30edd680-ccbd-11ea-817b-9d6ecff0e7de.png)

target framework: netcoreapp3.1

**Comment by henon** [comment]
it works for me. I'll push this sample project in a minute

![image](https://user-images.githubusercontent.com/44090/88258584-c63e9a00-ccc0-11ea-8c31-7a15b08387c4.png)

**Comment by StijnVA** [comment]
Thanks for the example, I can confirm it works. The problem is reproachable by adding the Keras.NET nuget reference. But that is not a problem for here I guess.
