### ISSUE TITLE
Not possible to use wheel file that's present in file system

### ISSUE THREAD

**Issue by markvandeveerdonk** [henon/Python.Included#18]
I'm facing the issue we're I'll be pulling in a wheel file from a nuget package (as I'm building a C# project, obviously). I see a way for that wheel file to be embedded as a resource. So I would like to just ship the wheel as a separate file and load it at runtime.

**Comment by henon** [comment]
I definitely is worth having a method to install wheels from a file path. Thanks for adding it.
