### ISSUE TITLE
Library should only delete self-created wheel files

### ISSUE THREAD

**Issue by katjoek** [henon/Python.Included#21]
Currently, the 
```InstallWheel(string wheelPath, bool force = false)```
method deletes the wheel file it installs. That's not good. The library should only auto-delete the wheel files it creates itself.

**Comment by katjoek** [comment]
Please create a new nuget release when you can. Thanks!

**Comment by henon** [comment]
ok, you got it.

**Comment by katjoek** [comment]
Thanks!

> Op 16 sep. 2020 om 13:07 heeft Meinrad Recheis <notifications@github.com> het volgende geschreven:
> 
> ﻿
> ok, you got it.
> 
>
