### ISSUE TITLE
Can I change the pip install source url though "-i",like usual in python environment?

### ISSUE THREAD

**Issue by zeugmato** [henon/Python.Included#25]
As usual,I often changed the pip install source url to like "https://.............." through "-i".Is there any argument to implement it?
And then, if I want to use such as pandas, numpy, every time must I install them?Can I  install one time  then use them directly forever?Thanks.

**Comment by henon** [comment]
I think you'll have to add support for -i in `PipInstallModule` and\or `PipInstallWheel`.

Your second question: Once a library is installed the deployment routine will find it and not redeploy, you can try this out.

**Comment by zeugmato** [comment]
Yeah, it works! Thanks a lot for your guidance. How excellent python.included is!

**Comment by henon** [comment]
Can you PR the change so others can benefit from it too?

**Comment by zeugmato** [comment]
Maybe I didn’t make it clear just now, I just added a '-i' option.For example,I want to pip install the famous package 'pandas' ,so use  Installer.PipInstallModule("pandas -i https://pypi.douban.com/simple"). So I can get a faster download speed. Can this be pulled requests? I have no idea because I am  a freshman with github.

**Comment by henon** [comment]
Oh I see, no need then, everyone can just pass whatever they need. Thanks for clarifying.
