### ISSUE TITLE
Running under Debian Linux - python37 not found

### ISSUE THREAD

**Issue by alishchytovych** [henon/Python.Included#28]
I'm trying to run the sample program under the Debian Linux and get the error:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'python37' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpython37: cannot open shared object file: No such file or directory
   at Python.Runtime.Runtime.Py_IsInitialized()
```
Also I've checked that in the ~/.local/share I have python3.7 but this is Windows distribution. Debian itself has python3.7 installed as well. 

Is it possible to have Linux python distribution included into Python.Included?

**Comment by henon** [comment]
yes. others have done so successfully. you'll find a closed thread on linux / mac support which might give you hints. anyhow, I am not a linux user. I just merged the linux support others have donated and taken their word that it works. you might want to look under the hood. the code is not complicated and you'll probably quickly find why it doesn't work for you.

**Comment by alishchytovych** [comment]
This resolves the issue on Debian 10 
```
apt install libpython3-dev
ln /usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython3.7.so /usr/lib/python3.7/config-3.7m-x86_64-linux-gnu/libpython37.so
```
and adding to the code
```
PythonEnv.DeployEmbeddedPython = false;
```

btw, kindly ask to fix in the code - the command should be in the quotes: $"/bin/bash -c \"{command}\""

**Comment by henon** [comment]
Can you send a Pull Request with the change? I'll merge and update the nuget.
