### ISSUE TITLE
Install path with spaces is not handled within Curl

### ISSUE THREAD

**Issue by jordanyssim** [henon/Python.Included#31]
Hi there, I've found that I can't get Python.Included working in my program because of a space within the install path. I'm following the example in [Python.Deployment.Download](https://github.com/henon/Python.Included/blob/master/examples/Python.Deployment.Download/Program.cs). 

My install path turns out as: `C:\\Users\\Jordan Sim\\Documents\\GitHub\\PythonIncludedTest\\bin\\Debug`

And the CLI runs curl as: `cmd.exe /C curl https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-amd64.zip -o C:\Users\Jordan Sim\Documents\GitHub\PythonIncludedTest\bin\Debug\python-3.7.3-embed-amd64.zip`

Which returns: `curl: (6) Could not resolve host: Sim\Documents\GitHub\PythonIncludedTest\bin\Debug\python-3.7.3-embed-amd64.zip`

Putting quotes around the install path results in `System.ArgumentException: 'Illegal characters in path.'`

**Comment by henon** [comment]
Can you check out the source code and try to find a solution? I'll gladly accept a PR and release a fixed package
