### ISSUE TITLE
`TryInstallPip` should return true if `pip` is already installed

### ISSUE THREAD

**Issue by JimiC** [henon/Python.Included#42]
In my opinion, the returned value of `IsPipInstalled` should be returned.

- https://github.com/henon/Python.Included/blob/11b6b2a29b8ce57bbcd8cfe3722efa4467cd154d/Python.Included/Installer.cs#L211
- https://github.com/henon/Python.Included/blob/eb0cce2a7599a23e38cfb669cd86abff04ca37e2/Python.Deployment/Installer.cs#L343

On first use, `TryInstallPip` returns `true` but if you call it again when `pip` is already installed it returns `false`. I'm expecting the return value to be `true` if `pip` is already installed.

**Comment by henon** [comment]
Done

https://www.nuget.org/packages/Python.Deployment/1.5.0
https://www.nuget.org/packages/Python.Included/3.10.0-preview5
