### ISSUE TITLE
argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by danijerez** [henon/Python.Included#49]
I was trying to do a simple test to use whisper.

 On the line:
`dynamic whisper = Py.Import("whisper");`

gives the following error: 
**argument of type 'NoneType' is not iterable**

check the version of python and it is **3.11** which is theoretically compatible

```
class Program
    {
        static async Task Main(string[] args)
        {
            await Installer.SetupPython();
            await Installer.TryInstallPip();
            await Installer.PipInstallModule("openai-whisper");
            PythonEngine.Initialize();
            using (Py.GIL())
            {
                dynamic whisper = Py.Import("whisper");
                var model = whisper.load_model("base");
                var result = model.transcribe("/path/to/audio/file.wav");
                Console.WriteLine(result["text"]);
            }
        }
    }
```

Any idea what could happen?

**Comment by henon** [comment]
Can you please check if this happens with plain Pythonnet too? If so, it would not be a bug of Python.Included which only supplies different deployment routines

**Comment by danijerez** [comment]
I have tried it directly as you have told me and the exact same thing happens.

**Comment by henon** [comment]
Ok, then I would suggest you post the issue on the pythonnet repo. I hope they can help you.
