### ISSUE TITLE
Allow pip on embedded python

### ISSUE THREAD

**Issue by epignatelli** [henon/Python.Included#5]
It seems like pip is not included, and officially supported in the embedded python version.
Although, many do use this workaround: https://github.com/pypa/pip/issues/4207#issuecomment-281236055

Would it created any drawback if Python.Included aligned with that?

**Comment by henon** [comment]
I don't know. It would be awesome if Python.Included could install more complex packages

**Comment by epignatelli** [comment]
I'll put together a small proposal, so we have some code to talk on.

**Comment by epignatelli** [comment]
@henon I raised a pr to explore the possibility. 
A bit of context, I am using that code with Keras.NET, because right now it relies on a local python installation.
Installing the whl only - the same way Numpy.Net does - does not guarantee dependencies, so a full pip behaviour is necessary.
It works fine for me - no drawbacks for now.

**Comment by henon** [comment]
@epignatelli thanks for your outstanding work!

**Comment by epignatelli** [comment]
np - closing this as it has been solved by https://github.com/henon/Python.Included/pull/6

**Comment by 0xzz** [comment]
This is an awesome feature! @henon Could you push this update to Nuget please?

**Comment by henon** [comment]
I just did: https://www.nuget.org/packages/Python.Included/3.7.3.3
