### ISSUE TITLE
.NET Core and error with ImportModule

### ISSUE THREAD

**Issue by rcalado** [henon/Python.Included#61]
Imported project into a new .NET core MVC  application and also into an AWS C# Lambda project.

Both projects are throwing 'PythonEngine' does not contain a definition for 'ImportModule'.

Is there a way to leverage your component within a .NET Core application?

Just trying to get the basic setup implemented and running into issues

 await Installer.SetupPython();
            PythonEngine.Initialize();
            dynamic sys=PythonEngine.ImportModule("sys");
            Console.WriteLine("Python version: " + sys.version);

**Comment by henon** [comment]
Which version of Python.Included and which Version of .NET Core?

.Net Core is supported. We have an example project in the repo that demonstrates it. Maybe it has to be updated for newer versions of Python.Included.

**Comment by rcalado** [comment]
.NET Core 6 and I didn't specify a Python Version.
I assumed that would grab the latest 3.11 version?

Didn't see a way to specify a lower version number to test against.
I didn't spot the .netcore3.1 sample earlier so thank you for alerting me to that.  
Unfortunately, there are some errors that still occur running that version against 3.1 or 6.0

See below for the console logs.  

Downloading Pip...
Downloading Pip...
Downloading Pip...
There was a problem downloading pip: The process cannot access the file 'C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64\Lib\get-pip.py' because it is being used by another process.
There was a problem downloading pip: The process cannot access the file 'C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64\Lib\get-pip.py' because it is being used by another process.
> cmd.exe /C "C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64\Scripts\pip" install "spacy"
> cmd.exe /C "C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64\Scripts\pip" install "spacy"


The system cannot find the path specified.

The system cannot find the path specified.

 => exit code 1
 => exit code 1
Could not find platform dependent libraries <exec_prefix>
0.05%
0.60%
1.23%
1.85%
2.47%
3.09%
3.72%
4.34%
4.96%
5.58%
6.20%
6.83%
7.45%
8.07%
8.69%
9.32%
9.94%
10.56%
11.18%
11.81%
12.43%
13.05%
13.67%
14.30%
15.27%
15.89%
16.52%
17.14%
17.76%
18.38%
19.01%
19.63%
20.25%
20.87%
21.50%
22.12%
22.74%
23.36%
23.99%
24.99%
25.61%
26.23%
26.86%
27.48%
28.10%
28.72%
29.35%
29.97%
30.59%
31.21%
31.84%
32.46%
33.08%
33.70%
34.71%
35.33%
36.10%
36.72%
37.48%
38.11%
38.73%
39.35%
39.97%
40.60%
41.22%
41.84%
42.46%
43.09%
43.71%
44.33%
44.95%
45.58%
46.20%
46.82%
47.44%
48.07%
48.69%
49.31%
49.93%
50.56%
51.18%
51.80%
52.42%
53.05%
53.67%
54.29%
54.91%
55.53%
56.16%
56.78%
57.40%
58.02%
58.65%
59.70%
60.32%
60.94%
61.56%
62.19%
62.81%
63.43%
64.05%
64.68%
65.30%
65.92%
66.54%
67.17%
67.79%
68.41%
69.03%
69.66%
70.28%
70.90%
71.52%
72.15%
72.77%
73.39%
74.01%
74.64%
75.26%
75.88%
76.50%
77.13%
77.75%
78.37%
78.99%
79.62%
80.24%
80.86%
81.48%
82.10%
82.73%
83.35%
83.97%
84.59%
85.22%
85.84%
86.46%
87.08%
87.71%
88.85%
89.47%
90.10%
90.72%
91.34%
91.96%
92.59%
93.21%
93.83%
94.45%
95.08%
95.70%
96.32%
96.94%
97.57%
98.19%
98.81%
100.00%
Done!
> cmd.exe /C cd "C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64" && python.exe Lib\get-pip.py
### Python version:
        3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
### Current working directory:
        C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0
### PythonPath:
        C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64\python311.zip;C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64\Lib;C:\Temp\Python.Included-main\Python.Included-main\examples\Python.Included.Example.NetCore\bin\Debug\net6.0\python-3.11.0-embed-amd64\DLLs

**Comment by henon** [comment]
OK, I fixed the problem.`RunCommand` which was called by `PipInstallModule` had an error, it should have wrapped the command of cmd.exe /C in quotes. After I fixed this the .net core example runs fine with .net 6. Releasing new nugets.

**Comment by henon** [comment]
https://www.nuget.org/packages/Python.Deployment/2.0.5
https://www.nuget.org/packages/Python.Included/3.11.6
