### ISSUE TITLE
Allow to change python install path

### ISSUE THREAD

**Issue by Horgun** [henon/Python.Included#7]
Hi, thanks for the work you've done.
I was hoping to install python in a different location.
Can i open a PR where i create a property like this:
`public static string INSTALL_PATH { get; set; } = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);`

Allowing it to be changed but with the default being the one you've set?

Thanks.

**Comment by henon** [comment]
Of course, thank you!
