### ISSUE TITLE
Are older version of .NETFramework or .NETStandard supported?

### ISSUE THREAD

**Issue by vsarpe** [henon/Python.Included#9]
Asking because I am looking at adapting Python.Included for an existing project targeting .NETFramework 4.5.1. Wondering what dependencies in .NETStandard 2.0 are required and whether support for .NETStandard 1.0 or for .NETFramework 4.5 directly would be straightforward.

Not sure if this is the appropriate place to ask about this or on https://github.com/henon/pythonnet_netstandard.

**Comment by henon** [comment]
pythonnet originally supports .NETFramework. I forked it to support .NETStandard.

The difference between .NETFramework und .NETStandard is only one piece of code where pythonnet loads some configuration file from an assembly stream. Here is the relevant commit in pythonnet_netstandard: https://github.com/henon/pythonnet_netstandard/commit/5f95018c13ca56beeff9a0478b5823bb045d2772

I would argue that I don't see any problems with a .NETFramework application consuming a .NETStandard library. Are you having trouble with it?

**Comment by vsarpe** [comment]
So yes, my app targets 4.5.1 which means it only has support for .NETStandard 1.2 whereas Python.Included (the `GetManifestResourceStream`) depends on .NETStandard 2.0. A simply fix would be to target 4.6.1, but I would only do this as a last resort.

OK thanks for the pointer, I'll see what I can do.
